services:
  frigate:
    container_name: frigate
    privileged: false 
    restart: unless-stopped
    stop_grace_period: 30s
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "512mb"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./frigate/config:/config
      - ./frigate/storage:/media/frigate
      - type: tmpfs 
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "8971:8971"
      - "5000:5000" 
    environment:
      FRIGATE_RTSP_PASSWORD: "password"
    networks:
      - frigate-net

  mqtt:
    container_name: mosquitto
    image: eclipse-mosquitto:latest
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    ports:
      - "1883:1883"
      - "9001:9001"
    restart: always
    networks:
      - frigate-net

  webapp:
    container_name: webUI
    image: bucket-counter-web:prod
    build:
      context: ./web
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - frigate
      - mqtt
    volumes:
      - ./web/prisma:/app/prisma
    networks:
      - frigate-net

networks:
  frigate-net:
    driver: bridge


