FROM node:18-alpine

WORKDIR /app

RUN apk add --no-cache python3 make g++ sqlite && \
    npm install -g pnpm

COPY package.json pnpm-lock.yaml ./
RUN pnpm install

COPY . .

RUN npx prisma generate

EXPOSE 3000 5555

CMD ["pnpm","dev"]
